name: directed_graph_challenge
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip==22.2.2
  - pip:
      - click==8.1.3
      - flake8==5.0.4
      - mypy==0.971
      - pytest==7.1.2
      - pytest-cov==3.0.0
      - networkx==2.8.5
